#!/usr/bin/env bash
set -euo pipefail

bundle install
bundle exec jekyll build
pip install -r requirements.txt --quiet
mkdir -p junit-reports
python -m pytest tests/ --junitxml=junit-reports/TEST-results.xml
